stats = {

strength:{index:["strength"], format:["+"," to Strength"], editable:1},
dexterity:{index:["dexterity"], format:["+"," to Dexterity"], editable:1},
vitality:{index:["vitality"], format:["+"," to Vitality"], editable:1},
energy:{index:["energy"], format:["+"," to Energy"], editable:1},
life:{index:["life"], format:["+"," to Life"], editable:1},
mana:{index:["mana"], format:["+"," to Mana"], editable:1},
defense:{index:["defense"], format:["+"," Defense"], editable:1},
ar:{index:["ar"], format:["+"," to Attack Rating"], editable:1},
stamina:{index:["stamina"], format:["+"," to Stamina"], editable:1},
block:{index:["block"], format:["Base Block Chance: ","%"], editable:1},
base_defense:{index:["base_defense"], format:["Base Defense: ",""], editable:1},

fRes_max:{index:["fRes_max"], format:["+","% to Maximum Fire Resist"], editable:1},
cRes_max:{index:["cRes_max"], format:["+","% to Maximum Cold Resist"], editable:1},
lRes_max:{index:["lRes_max"], format:["+","% to Maximum Lightning Resist"], editable:1},
pRes_max:{index:["pRes_max"], format:["+","% to Maximum Poison Resist"], editable:1},
mRes_max:{index:["mRes_max"], format:["+","% to Maximum Magic Resist"], editable:1},
fRes:{index:["fRes"], format:["Fire Resist +","%"], editable:1},
cRes:{index:["cRes"], format:["Cold Resist +","%"], editable:1},
lRes:{index:["lRes"], format:["Lightning Resist +","%"], editable:1},
pRes:{index:["pRes"], format:["Poison Resist +","%"], editable:1},
mRes:{index:["mRes"], format:["Magic Resist +","%"], editable:1},
cdr:{index:["cdr"], format:["+","% Cooldown Rate"], editable:1},
fcr:{index:["fcr"], format:["+","% Faster Cast Rate"], editable:1},
fbr:{index:["fbr"], format:["+","% Faster Block Rate"], editable:1},
fhr:{index:["fhr"], format:["+","% Faster Hit Recovery"], editable:1},
frw:{index:["frw"], format:["+","% Faster Run/Walk"], editable:1},
ias:{index:["ias"], format:["+","% Increased Attack Speed"], editable:1},
wias:{index:["wias"], format:["+"," On Weapon IAS"], editable:1},
offwepias:{index:["offwepias"], format:["+"," Off Weapon IAS"], editable:1},
pierce:{index:["pierce"], format:["Pierce ","%"], editable:1},
cblow:{index:["cblow"], format:["","% Chance of Crushing Blow"], editable:1},
dstrike:{index:["dstrike"], format:["","% Deadly Strike"], editable:1},
cstrike:{index:["cstrike"], format:["","% Critical Strike"], editable:1},
owounds:{index:["owounds"], format:["","% Chance of Open Wounds"], editable:1},
fDamage:{index:["fDamage"], format:["+","% to Fire Skill Damage"], editable:1},
cDamage:{index:["cDamage"], format:["+","% to Cold Skill Damage"], editable:1},
lDamage:{index:["lDamage"], format:["+","% to Lightning Skill Damage"], editable:1},
pDamage:{index:["pDamage"], format:["+","% to Poison Skill Damage"], editable:1},
mDamage:{index:["mDamage"], format:["+","% to Magic Skill Damage"], editable:1},
fPierce:{index:["fPierce"], format:["Fire Pierce ","%"], editable:1},
cPierce:{index:["cPierce"], format:["Cold Pierce ","%"], editable:1},
lPierce:{index:["lPierce"], format:["Lightning Pierce ","%"], editable:1},
pPierce:{index:["pPierce"], format:["Poison Pierce ","%"], editable:1},
mPierce:{index:["mPierce"], format:["Magic Pierce ","%"], editable:1},
pdr:{index:["pdr"], format:["Damage Reduced by ","%"], editable:1},
damage_reduced:{index:["damage_reduced"], format:["Damage Reduced by ",""], editable:1},
mDamage_reduced:{index:["mDamage_reduced"], format:["Magic and Elemental Damage Reduced by ",""], editable:1},
mf:{index:["mf"], format:["","% Better Chance of Getting Magic Items"], editable:1},
gf:{index:["gf"], format:["","% Extra Gold from Monsters"], editable:1},
life_leech:{index:["life_leech"], format:["","% Life Stolen per Hit"], editable:1},
mana_leech:{index:["mana_leech"], format:["","% Mana Stolen per Hit"], editable:1},
life_per_hit:{index:["life_per_hit"], format:["+"," Life gained on Melee Hit"], editable:1},
mana_per_hit:{index:["mana_per_hit"], format:["+"," Mana gained on Melee Hit"], editable:1},
life_per_ranged_hit:{index:["life_per_ranged_hit"], format:["+"," Life gained on Ranged Hit"], editable:1},
mana_per_ranged_hit:{index:["mana_per_ranged_hit"], format:["+"," Mana gained on Ranged Hit"], editable:1},
fAbsorb:{index:["fAbsorb"], format:["Fire Absorb ","%"], editable:1},
cAbsorb:{index:["cAbsorb"], format:["Cold Absorb ","%"], editable:1},
lAbsorb:{index:["lAbsorb"], format:["Lightning Absorb ","%"], editable:1},
fAbsorb_flat:{index:["fAbsorb_flat"], format:["+"," Fire Absorb"], editable:1},
cAbsorb_flat:{index:["cAbsorb_flat"], format:["+"," Cold Absorb"], editable:1},
lAbsorb_flat:{index:["lAbsorb_flat"], format:["+"," Lightning Absorb"], editable:1},
mAbsorb_flat:{index:["mAbsorb_flat"], format:["+"," Magic Absorb"], editable:1},
dae:{index:["dae"], format:["","/","","/",""]},

all_skills:{index:["all_skills"], format:["+"," to All Skills"], editable:1},
all_attributes:{index:["all_attributes"], format:["+"," to all Attributes"], editable:1},
all_res:{index:["all_res"], format:["All Resistances +",""], editable:1},
velocity:{index:["velocity"], format:["","% Faster Run/Walk"], editable:1},
max_life:{index:["max_life"], format:["Increase Maximum Life ","%"], editable:1},
max_mana:{index:["max_mana"], format:["Increase Maximum Mana ","%"], editable:1},
max_stamina:{index:["max_stamina"], format:["Increase Maximum Stamina ","%"], editable:1},
damage_bonus:{index:["damage_bonus"], format:["+","% Enhanced Damage"], friendly:["Off-Weapon Enhanced Damage"], editable:1},
defense_bonus:{index:["defense_bonus"], format:["+","% Enhanced Defense"], editable:1},
ar_bonus:{index:["ar_bonus"], format:["","% Bonus to Attack Rating"], editable:1},
ar_bonus_per_level:{index:["ar_bonus_per_level","ar_bonus_per_level"], format:["Attack Rating +","% (","% per level)"], mult:["level",1], editable:1},
max_energy:{index:["max_energy"], format:["Max Energy: +","%"], editable:1},
ias_per_8_dexterity:{index:["ias_per_8_dexterity"], format:["+","% Increased Attack Speed per 8 Dexterity"], editable:1},
ar_per_socketed:{index:["ar_per_socketed"], format:["+"," Attack Rating per socketed gem/rune"], editable:1},
all_skills_ember:{index:["all_skills_ember"], format:["+"," to All Skills when 5 Ember Charges are active"]},
baseSpeed:1,//{index:["baseSpeed"], format:["Weapon Speed: +",""]},

life_per_level:{index:["life_per_level","life_per_level"], format:["+"," to Life ("," per level)"], mult:["level",1], editable:1},
mana_per_level:{index:["mana_per_level","mana_per_level"], format:["+"," to Mana ("," per level)"], mult:["level",1], editable:1},
defense_per_level:{index:["defense_per_level","defense_per_level"], format:["+"," Defense ("," per level)"], mult:["level",1], editable:1},
ar_per_level:{index:["ar_per_level","ar_per_level"], format:["+"," to Attack Rating ("," per level)"], mult:["level",1], editable:1},
stamina_per_level:{index:["stamina_per_level","stamina_per_level"], format:["+"," Stamina ("," per level)"], mult:["level",1], editable:1},
strength_per_level:{index:["strength_per_level","strength_per_level"], format:["+"," to Strength ("," per level)"], mult:["level",1], editable:1},
dexterity_per_level:{index:["dexterity_per_level","dexterity_per_level"], format:["+"," to Dexterity ("," per level)"], mult:["level",1], editable:1},
vitality_per_level:{index:["vitality_per_level","vitality_per_level"], format:["+"," to Vitality ("," per level)"], mult:["level",1], editable:1},
fRes_per_level:{index:["fRes_per_level","fRes_per_level"], format:["Fire Resist +","% (","% per level)"], mult:["level",1], editable:1},
cRes_per_level:{index:["cRes_per_level","cRes_per_level"], format:["Cold Resist +","% (","% per level)"], mult:["level",1], editable:1},
lRes_per_level:{index:["lRes_per_level","lRes_per_level"], format:["Lightning Resist +","% (","% per level)"], mult:["level",1], editable:1},
pRes_per_level:{index:["pRes_per_level","pRes_per_level"], format:["Poison Resist +","% (","% per level)"], mult:["level",1], editable:1},
fAbsorb_flat_per_level:{index:["fAbsorb_flat_per_level","fAbsorb_flat_per_level"], format:["Fire Absorb +"," ("," per level)"], mult:["level",1], editable:1},
cAbsorb_flat_per_level:{index:["cAbsorb_flat_per_level","cAbsorb_flat_per_level"], format:["Cold Absorb +"," ("," per level)"], mult:["level",1], editable:1},
mf_per_level:{index:["mf_per_level","mf_per_level"], format:["","% Better Chance of Getting Magic Items (","% per level)"], mult:["level",1], editable:1},
gf_per_level:{index:["gf_per_level","gf_per_level"], format:["","% Extra Gold from Monsters (","% per level)"], mult:["level",1], editable:1},
fcr_per_level:{index:["fcr_per_level","fcr_per_level"], format:["+","% Faster Cast Rate (","% per level)"], mult:["level",1], editable:1},
dstrike_per_level:{index:["dstrike_per_level","dstrike_per_level"], format:["","% Deadly Strike (","% per level)"], mult:["level",1], editable:1},
e_def_per_level:{index:["e_def_per_level","e_def_per_level"], format:["+","% Enhanced Defense (","% per level)"], mult:["level",1], editable:1},

base_damage_min:{index:["base_damage_min","base_damage_max"], format:["Base Damage: ","-",""]},
base_damage_max:1,
damage_min:{index:["damage_min","damage_max"], format:["Adds ","-"," Damage"], alt:"base_damage_max", friendly:["Adds Damage - Min"], editable:1},
damage_max:{index:["damage_min","damage_max"], format:["Adds ","-"," Damage"], alt:"base_damage_min", friendly:["Adds Damage - Max"], editable:1},
fDamage_min:{index:["fDamage_min","fDamage_max"], format:["Adds ","-"," Fire Damage"], alt:"fDamage_max", friendly:["Adds Fire Damage - Min"], editable:1},
fDamage_max:{index:["fDamage_min","fDamage_max"], format:["Adds ","-"," Fire Damage"], alt:"fDamage_min", friendly:["Adds Fire Damage - Max"], editable:1},
cDamage_min:{index:["cDamage_min","cDamage_max"], format:["Adds ","-"," Cold Damage"], alt:"cDamage_max", friendly:["Adds Cold Damage - Min"], editable:1},
cDamage_max:{index:["cDamage_min","cDamage_max"], format:["Adds ","-"," Cold Damage"], alt:"cDamage_min", friendly:["Adds Cold Damage - Max"], editable:1},
lDamage_min:{index:["lDamage_min","lDamage_max"], format:["Adds ","-"," Lightning Damage"], alt:"lDamage_max", friendly:["Adds Light Damage - Min"], editable:1},
lDamage_max:{index:["lDamage_min","lDamage_max"], format:["Adds ","-"," Lightning Damage"], alt:"lDamage_min", friendly:["Adds Light Damage - Max"], editable:1},
pDamage_min:{index:["pDamage_min","pDamage_max","pDamage_duration"], format:["Adds ","-"," Poison Damage over "," seconds"], alt:"pDamage_max", friendly:["Adds Poison Damage - Min"], editable:1},
pDamage_max:{index:["pDamage_min","pDamage_max","pDamage_duration"], format:["Adds ","-"," Poison Damage over "," seconds"], alt:"pDamage_min", friendly:["Adds Poison Damage - Min"], editable:1},
pDamage_all:{index:["pDamage_all","pDamage_duration"], format:["+"," Poison Damage over "," seconds"], editable:1},
pDamage_duration:1,
pDamage_duration_override:{index:["pDamage_duration_override"], format:["Poison damage delivered by your weapon always lasts "," seconds"], editable:1},
mDamage_min:{index:["mDamage_min","mDamage_max"], format:["Adds ","-"," Magic Damage"], alt:"mDamage_max", friendly:["Adds Magic Damage - Min"], editable:1},
mDamage_max:{index:["mDamage_min","mDamage_max"], format:["Adds ","-"," Magic Damage"], alt:"mDamage_min", friendly:["Adds Magic Damage - Max"], editable:1},

ftick_min:{index:["ftick_min","ftick_max"],format:["Aura tick does ","-"," Fire damage"],alt:"ftick_max"},
ftick_max:{index:["ftick_min","ftick_max"],format:["Aura tick does ","-"," Fire damage"],alt:"ftick_min"},
ctick_min:{index:["ctick_min","ctick_max"],format:["Aura tick does ","-"," Cold damage"],alt:"ctick_max"},
ctick_max:{index:["ctick_min","ctick_max"],format:["Aura tick does ","-"," Cold damage"],alt:"ctick_min"},
ltick_min:{index:["ltick_min","ltick_max"],format:["Aura tick does ","-"," Lightning damage"],alt:"ltick_max"},
ltick_max:{index:["ltick_min","ltick_max"],format:["Aura tick does ","-"," Lightning damage"],alt:"ltick_min"},
mtick_min:{index:["mtick_min","mtick_max"],format:["Aura tick does ","-"," Magic damage"],alt:"mtick_max"},
mtick_max:{index:["mtick_min","mtick_max"],format:["Aura tick does ","-"," Magic damage"],alt:"mtick_min"},
//mDamage_max:1,
min_damage_per_level:{index:["min_damage_per_level","min_damage_per_level"], format:["+"," to Minimum Damage ("," per level)"], mult:["level",1], editable:1},
max_damage_per_level:{index:["max_damage_per_level","max_damage_per_level"], format:["+"," to Maximum Damage ("," per level)"], mult:["level",1], editable:1},
fDamage_max_per_level:{index:["fDamage_max_per_level","fDamage_max_per_level"], format:["+"," to Maximum Fire Damage ("," per level)"], mult:["level",1], editable:1},
cDamage_max_per_level:{index:["cDamage_max_per_level","cDamage_max_per_level"], format:["+"," to Maximum Cold Damage ("," per level)"], mult:["level",1], editable:1},
kick_min:1,
kick_damage_per_level:{index:["kick_damage_per_level","kick_damage_per_level"], format:["+"," Kick Damage ("," per level)"], mult:["level",1], editable:1},
smite_min:{index:["smite_min","smite_max"], format:["Smite Damage: ","-",""]},
smite_max:1,
e_damage:{index:["e_damage"], format:["+","% Enhanced Damage"], friendly:["On-Weapon Enhanced Damage"], editable:1},
e_max_damage_per_level:{index:["e_max_damage_per_level","e_max_damage_per_level"], format:["+","% Enhanced Maximum Damage (","% per level)"], mult:["level",1], editable:1},
lDamage_max_per_2_energy:{index:["lDamage_max_per_2_energy"], format:["+"," Lightning Damage per 2 Energy"], editable:1},
cDamage_per_ice:{index:["cDamage_per_ice"], format:["+"," Cold Damage per Ice Charge"]},
cDamage_per_socketed:{index:["cDamage_per_socketed"], format:["+"," Cold Damage per socketed Gem/Rune"], editable:1},

ctc:2,
cskill:2,
ibc:{index:["ibc"], format:["","% Increased Block Chance"], editable:1},
life_per_kill:{index:["life_per_kill"], format:["+"," Life after each Kill"], editable:1},
mana_per_kill:{index:["mana_per_kill"], format:["+"," Mana after each Kill"], editable:1},
//life_replenish:{index:["life_replenish"], format:["Replenish Life +",""]},
life_replenish:{index:["life_replenish"], format:["Replenish Life"," per Second"], editable:1},
life_regen:{index:["life_regen"], format:["Regenerate Life ","%"], editable:1},
mana_regen:{index:["mana_regen"], format:["Regenerate Mana ","%"], editable:1},
damage_to_mana:{index:["damage_to_mana"], format:["","% Damage Taken Gained as Mana when Hit"], editable:1},
missile_defense:{index:["missile_defense"], format:["+"," Defense vs Missile"], editable:1},
melee_defense:{index:["melee_defense"], format:["+"," Defense vs Melee"], editable:1},
damage_vs_demons:{index:["damage_vs_demons"], format:["+","% Damage to Demons"], editable:1},
damage_vs_undead:{index:["damage_vs_undead"], format:["+","% Damage to Undead"], editable:1},
ar_vs_demons:{index:["ar_vs_demons"], format:["+"," to Attack Rating against Demons"], editable:1},
ar_vs_undead:{index:["ar_vs_undead"], format:["+"," to Attack Rating against Undead"], editable:1},
ar_vs_undead_per_level:{index:["ar_vs_undead_per_level","ar_vs_undead_per_level"], format:["+"," to Attack Rating against Undead ("," per level)"], mult:["level",1], editable:1},
damage_vs_undead_per_level:{index:["damage_vs_undead_per_level","damage_vs_undead_per_level"], format:["+","% Damage to Undead (","% per level)"], mult:["level",1], editable:1},
damage_vs_demons_per_level:{index:["damage_vs_demons_per_level","damage_vs_demons_per_level"], format:["+","% Damage to Demons (","% per level)"], mult:["level",1], editable:1},
life_per_demon_kill:{index:["life_per_demon_kill"], format:[""," life gained per Demon killed"], editable:1},
thorns_lightning:{index:["thorns_lightning"], format:["Attacker Takes Lightning Damage of ",""], editable:1},
thorns:{index:["thorns"], format:["Attacker Takes Damage of ",""], editable:1},
thorns_per_level:{index:["thorns_per_level","thorns_per_level"], format:["Attacker Takes Damage of "," ("," per level)"], mult:["level",1], editable:1},
thorns_reflect:{index:["thorns_reflect"], format:["","% Damage Returned"], editable:1},
poison_length_reduced:{index:["poison_length_reduced"], format:["Poison Length Reduced by ","%"], editable:1},
curse_length_reduced:{index:["curse_length_reduced"], format:["Curse Length Reduced by ","%"], editable:1},
light_radius:{index:["light_radius"], format:["+"," to Light Radius"], editable:1},
slower_stam_drain:{index:["slower_stam_drain"], format:["","% Slower Stamina Drain"], editable:1},
heal_stam:{index:["heal_stam"], format:["Heal Stamina +","%"], editable:1},
heal_stam_per_level:{index:["heal_stam_per_level","heal_stam_per_level"], format:["Heal Stamina +","% (","% per level)"], mult:["level",1], editable:1},
discount:{index:["discount"], format:["Vendor Prices Reduced by ","%"], editable:1},

enemy_fRes:{index:["enemy_fRes"], format:["","% to Enemy Fire Resistance"], editable:1},
enemy_cRes:{index:["enemy_cRes"], format:["","% to Enemy Cold Resistance"], editable:1},
enemy_lRes:{index:["enemy_lRes"], format:["","% to Enemy Lightning Resistance"], editable:1},
enemy_pRes:{index:["enemy_pRes"], format:["","% to Enemy Poison Resistance"], editable:1},
enemy_mRes:{index:["enemy_mRes"], format:["","% to Enemy Magic Resistance"], editable:1},
enemy_defense:{index:["enemy_defense"], format:["Enemy Defense ","%"], editable:1},
enemy_defense_flat:{index:["enemy_defense_flat"], format:["Enemy Defense ",""], editable:1},
target_defense:{index:["target_defense"], format:["Target Defense ","%"], editable:1},
monster_defense_per_hit:{index:["monster_defense_per_hit"], format:[""," to Monster Defense per Hit"], editable:1},
slows_target:{index:["slows_target"], format:["Slow Target by ","%"], editable:1},
slow_enemies:{index:["slow_enemies"], format:["Enemies slowed by ","%"], editable:1},
freezes_target:{index:["freezes_target"], format:["Freezes Target +",""], editable:1},
flee_on_hit:{index:["flee_on_hit"], format:["Hit Causes Monster to Flee ","%"], editable:1},
blind_on_hit:{index:["blind_on_hit"], format:["Hit Blinds Target +",""], editable:1},

itd:{index:[], format:["Ignore Target Defense"], editable:1},
pmh:{index:[], format:["Prevent Monster Heal"], editable:1},
cbf:{index:[], format:["Cannot be Frozen"], editable:1},
peace:{index:[], format:["Slain Enemies rest in Peace"], editable:1},
knockback:{index:[], format:["Knockback"], editable:1},
half_freeze:{index:[], format:["Half Freeze Duration"], editable:1},
melee_splash:{index:[], format:["Melee Attacks deal Splash Damage"], editable:1},
metamorphosis_wolf:{index:[], format:["<br>Werewolf Form specific changes:"]},
metamorphosis_wolf1:{index:[], format:["-(10-15%)% to Enemy Poison Resists affected by Rabies"]}, //format:[[skill_Summon_Dire_Wolf:5]],
metamorphosis_bear:{index:[], format:["<br>Werebear Form specific changes:"]},
metamorphosis_bear1:{index:[], format:["Gain Attacks cleave during Maul buff (cleave level based on Maul charge count)"]},
metamorphosis_bear2:{index:[], format:["Grizzly Bear gains Attacks cleave during Maul buff (cleave level based on Maul charge count)<br>"]},
glow:1,
fade:1,

sockets:{index:["sockets"], format:["Socketed (",")"], editable:1},
e_def:{index:["e_def"], format:["+","% Enhanced Defense"], editable:1},
req:{index:["req"], format:["Requirements +","%"], editable:1},
ethereal:{index:[], format:["Ethereal"], editable:1},
indestructible:{index:[], format:["Indestructible"], editable:1},
autorepair:{index:[], format:["Durability Repairs over Time"], editable:1},
autoreplenish:{index:[], format:["Quantity Replenishes over Time"], editable:1},
stack_size:{index:[], format:["Increased Stack Size"], editable:1},
twoHanded:1,
twoHands:1,
range:1,//{index:["range"], format:["Range: ",""]},
throw_min:{index:["throw_min","throw_max"], format:["Throw Damage: ","-",""], alt:"throw_max",  friendly:["Thrown Damage - Min"], editable:1},
throw_max:{index:["throw_min","throw_max"], format:["Throw Damage: ","-",""], alt:"throw_min",  friendly:["Thrown Damage - Max"], editable:1},
//throw_max:1,
base_min_alternate:1,//{index:["base_damage_min","base_damage_max"], format:["Base One-Handed Damage: ","-",""]},
base_max_alternate:1,
def_low:1,
def_high:1,
durability:{index:["durability"], format:["Durability: ",""]},
max_sockets:1,
tier:1,
nonmetal:1,
name:1,
group:1,
type:1,
set_bonuses:1,
rarity:1,
size:{index:["size"], format:[""," Charm"]},
not:1,
only:1,
upgrade:1,
downgrade:1,
aura:{index:["aura_lvl","aura"], format:["Level "," "," Aura when Equipped"]},
aura_lvl:1,
issalvation:0,
special:1,
pod_changes:1,
sup:1,//{index:["sup"], format:["Superior +","%"]},
req_level:{index:["req_level"], format:["Required Level: ",""]},
req_strength:{index:["req_strength"], format:["Required Strength: ",""]},
req_dexterity:{index:["req_dexterity"], format:["Required Dexterity: ",""]},
quest:1,
UNIQUE:0,

set_IK:1,
set_Mav:1,
set_Gris:1,
set_TO:1,
set_TR:1,
set_Nat:1,
set_Ald:1,
set_BK:1,
set_Disciple:1,
set_Angelic:1,
set_Cathan:1,
set_Cow:1,
set_Brethren:1,
set_Hwanin:1,
set_Naj:1,
set_Orphan:1,
set_Sander:1,
set_Sazabi:1,
set_Arcanna:1,
set_Arctic:1,
set_Berserker:1,
set_Civerb:1,
set_Cleglaw:1,
set_Death:1,
set_Hsarus:1,
set_Infernal:1,
set_Iratha:1,
set_Isenhart:1,
set_Milabrega:1,
set_Sigon:1,
set_Tancred:1,
set_Vidala:1,
bonus_corpse_explosion:{index:["bonus_corpse_explosion"], format:["Corpse Explosion deals +","% of Maximum Corpse life"], editable:1},
phys_Lightning_Surge:{index:["phys_Lightning_Surge"], format:["Lightning Surge Deals ","% Extra Damage As Physical"], editable:1},
extraValkyrie:{index:[], format:["Can Summon One Additional Valkyrie"]},
extraGrizzly:{index:[], format:["Can Summon One Additional Grizzly Bear"]},
curseGrizzly:{index:[], format:["Summoned Grizzly Bear cannot be cursed"]},
extraFireGolem:{index:[], format:["Can Summon One Additional Fire Golem"]},
extraHydra:{index:[], format:["Can Summon One Additional Hydra"]},
radius_FreezingArrow:{index:["radius_FreezingArrow"], format:["+","% to Freezing Arrow Radius"], editable:1},
reset_cooldown_on_kill:{index:["reset_cooldown_on_kill"], format:["","% Chance to Reset Skill Cooldown on Kill"], editable:1},
cdr_on_striking:{index:["cdr_on_striking"], format:["","% Reduced Skill Cooldown For 4 Seconds On Striking"], editable:1},
cdr_on_kill:{index:["cdr_on_kill"], format:["","% Chance to Reduce Skill Cooldowns by 2 Seconds On Kill"], editable:1},
reanimate:{index:["reanimate"], format:["","% reanimate as: Returned"], editable:1},
half_Battle_Orders:{index:[], format:["Battle Order's life and mana bonuses are halved"]},
extra_Bone_Spears:{index:["extra_Bone_Spears"], format:["Bone Spear fires "," Additional Projectiles"]},
bonus_sanctuary_rate:{index:["bonus_sanctuary_rate"], format:["+","% Increased Sanctuary Area Damage Rate"]},
extra_arrows_Cold_Arrow:{index:["extra_arrows_Cold_Arrow"], format:["Cold Arrow Fires "," Additional Projectiles"], editable:1},
extra_arrows_Magic_Arrow:{index:["extra_arrows_Magic_Arrow"], format:["Magic Arrow Fires "," Additional Arrows"], editable:1},
extra_arrows_Fire_Arrow:{index:["extra_arrows_Fire_Arrow"], format:["Fire Arrow Fires "," Additional Arrows"], editable:1},
extra_arrows_Ice_Arrow:{index:["extra_arrows_Ice_Arrow"], format:["Ice Arrow Fires "," Additional Arrows"], editable:1},
extra_conversion_Magic_Arrow:{index:["extra_conversion_Magic_Arrow"], format:["+","% Magic Arrow Damage Converted to Magic"], editable:1},

flamme:{index:["flamme"], format:["","% of Life dealt per second as fire"], editable:1},
ias_skill:{index:["ias_skill"], format:["+","% Increased Attack Speed"]},
ar_shrine_bonus:{index:["ar_shrine_bonus"], format:["Attack Rating: +","%"], editable:1},
charge_ember:{index:["charge_ember"], format:[""," Ember Charges"]},
charge_thunder:{index:["charge_thunder"], format:[""," Thunder Charges"]},
charge_ice:{index:["charge_ice"], format:[""," Ice Charges"]},
summon_damage_bonus:{index:["summon_damage_bonus"], format:["Summon Damage: +","%"], editable:1},
hammer_bonus:{index:["hammer_bonus"], format:["Blessed Hammer Magic Damage: +","%"], editable:1},
hammer_on_hit:{index:["hammer_on_hit"], format:["Chance for you to cast Blessed Hammer on hit: ","%"], editable:1},
redeem_chance:{index:["redeem_chance"], format:["Chance to redeem soul: ","%"], editable:1},
redeem_amount:{index:["redeem_amount"], format:["Life/Mana recovered: ",""], editable:1},
absorb_elemental:{index:["absorb_elemental"], format:["Absorbs "," damage"], friendly:["Flat Elemental Damage Absorb"], editable:1},
absorb_melee:{index:["absorb_melee"], format:["Absorbs "," damage"], friendly:["Flat Physical Damage Absorb"], editable:1},
absorb_es_redirect:{index:["absorb_es_redirect"], format:["Absorbs ","%"], editable:1},
absorb_es_deplete:{index:["absorb_es_deplete"], format:["Efficiency: ","%"], editable:1},
duration:{index:["duration"], format:["Duration: "," seconds"], editable:1},
radius:{index:["radius"], format:["Radius: "," yards"]},
amountSummoned:1,
enemy_damage:1,
enemy_attack:1,
//enemy_physRes:1,
enemy_physRes:{index:["enemy_physRes"], format:["","% to Enemy Physical Resistance"], editable:1},
physicalDamage:{index:["physicalDamage"], format:["+","% Increased Physical Damage"], editable:1},
enemy_allRes:1,
fleeing:1,
flee_distance:1,
dimmedVision:1,
confused:1,
attraction:1,
enemy_ias:1,
enemy_frw:1,

base:{index:["base"], format:["base"], editable:1},
//base:1,
img:1,
original_tier:1,
weapon:1,
armor:1,
shield:1,
//debug:1,
debug:{index:[],format:['<span style="color:red; font-size:12px">'+"Item does not exist in game,<br>only exists here for ease of testing"+'</span>']},
damagetoohigh:{index:[],format:['<span style="color:red; font-size:12px">'+"Damage displayed here is much higher than in game damage "+'</span>']},
notupdated:{index:[],format:['<span style="color:red; font-size:12px">'+"Skill has not been updated to P22 Minium"+'</span>']},
//synth:0,
//0:1,
//1:1,
//2:1,
//3:1,
item_defense:1,
experience:{index:["experience"], format:["+","% Experience Gained"], editable:1},
durability_extra:{index:["durability_extra"], format:["+"," Durability"]},

skills_javelins:{index:["skills_javelins"], format:["+"," to Spear & Javelin Skills (Amazon only)"], editable:1},
skills_passives:{index:["skills_passives"], format:["+"," to Passive Skills (Amazon only)"], editable:1},
skills_bows:{index:["skills_bows"], format:["+"," to Bow & Crossbow Skills (Amazon only)"], editable:1},
skills_martial:{index:["skills_martial"], format:["+"," to Martial Arts (Assassin only)"], editable:1},
skills_shadow:{index:["skills_shadow"], format:["+"," to Shadow Disciplines (Assassin only)"], editable:1},
skills_traps:{index:["skills_traps"], format:["+"," to Traps (Assassin only)"], editable:1},
skills_warcries:{index:["skills_warcries"], format:["+"," to Warcries (Barbarian only)"], editable:1},
skills_masteries:{index:["skills_masteries"], format:["+"," to Masteries (Barbarian only)"], editable:1},
skills_combat_barbarian:{index:["skills_combat_barbarian"], format:["+"," to Combat Skills (Barbarian only)"], editable:1},
skills_elemental:{index:["skills_elemental"], format:["+"," to Elemental Skills (Druid only)"], editable:1},
skills_shapeshifting:{index:["skills_shapeshifting"], format:["+"," to Shapeshifting (Druid only)"], editable:1},
skills_summoning_druid:{index:["skills_summoning_druid"], format:["+"," to Summoning Skills (Druid only)"], editable:1},
skills_summoning_necromancer:{index:["skills_summoning_necromancer"], format:["+"," to Summoning Skills (Necromancer only)"], editable:1},
skills_poisonBone:{index:["skills_poisonBone"], format:["+"," to Poison & Bone Skills (Necromancer only)"], editable:1},
skills_curses:{index:["skills_curses"], format:["+"," to Curses (Necromancer only)"], editable:1},
skills_offensive:{index:["skills_offensive"], format:["+"," to Offensive Auras (Paladin only)"], editable:1},
skills_defensive:{index:["skills_defensive"], format:["+"," to Defensive Auras (Paladin only)"], editable:1},
skills_combat_paladin:{index:["skills_combat_paladin"], format:["+"," to Combat Skills (Paladin only)"], editable:1},
skills_cold:{index:["skills_cold"], format:["+"," to Cold Skills (Sorceress only)"], editable:1},
skills_lightning:{index:["skills_lightning"], format:["+"," to Lightning Skills (Sorceress Only)"], editable:1},
skills_fire:{index:["skills_fire"], format:["+"," to Fire Skills (Sorceress only)"], editable:1},

skills_amazon:{index:["skills_amazon"], format:["+"," to Amazon Skill Levels"], editable:1},
skills_assassin:{index:["skills_assassin"], format:["+"," to Assassin Skill Levels"], editable:1},
skills_barbarian:{index:["skills_barbarian"], format:["+"," to Barbarian Skill Levels"], editable:1},
skills_druid:{index:["skills_druid"], format:["+"," to Druid Skill Levels"], editable:1},
skills_necromancer:{index:["skills_necromancer"], format:["+"," to Necromancer Skill Levels"], editable:1},
skills_paladin:{index:["skills_paladin"], format:["+"," to Paladin Skill Levels"], editable:1},
skills_sorceress:{index:["skills_sorceress"], format:["+"," to Sorceress Skill Levels"], editable:1},

skills_fire_all:{index:["skills_fire_all"], format:["+"," to Fire Skills"], editable:1},
skills_cold_all:{index:["skills_cold_all"], format:["+"," to Cold Skills"], editable:1},
skills_poison_all:{index:["skills_poison_all"], format:["+"," to Poison Skills"], editable:1},
 
skills_ele_poison_all:{index:["skills_ele_poison_all"], format:["+"," to Elemental and Poison Skills"], editable:1},

skill_Jab:{index:["skill_Jab"], format:["+"," to Jab (Amazon only)"], editable:1},
skill_Power_Strike:{index:["skill_Power_Strike"], format:["+"," to Power Strike (Amazon only)"], editable:1},
skill_Poison_Javelin:{index:["skill_Poison_Javelin"], format:["+"," to Poison Javelin (Amazon only)"], editable:1},
skill_Fend:{index:["skill_Fend"], format:["+"," to Fend (Amazon only)"], editable:1},
skill_Lightning_Bolt:{index:["skill_Lightning_Bolt"], format:["+"," to Lightning Bolt (Amazon only)"], editable:1},
skill_Charged_Strike:{index:["skill_Charged_Strike"], format:["+"," to Charged Strike (Amazon only)"], editable:1},
skill_Plague_Javelin:{index:["skill_Plague_Javelin"], format:["+"," to Plague Javelin (Amazon only)"], editable:1},
skill_Molten_Strike:{index:["skill_Molten_Strike"], format:["+"," to Molten Strike (Amazon only)"], editable:1},
skill_Lightning_Strike:{index:["skill_Lightning_Strike"], format:["+"," to Lightning Strike (Amazon only)"], editable:1},
skill_Lightning_Fury:{index:["skill_Lightning_Fury"], format:["+"," to Lightning Fury (Amazon only)"], editable:1},
skill_Inner_Sight:{index:["skill_Inner_Sight"], format:["+"," to Inner Sight (Amazon only)"], editable:1},
skill_Lethal_Strike:{index:["skill_Lethal_Strike"], format:["+"," to Lethal Strike (Amazon only)"], editable:1},
skill_Phase_Run:{index:["skill_Phase_Run"], format:["+"," to Phase Run (Amazon only)"], editable:1},
skill_Dodge:{index:["skill_Dodge"], format:["+"," to Dodge (Amazon only)"], editable:1},
skill_Avoid:{index:["skill_Avoid"], format:["+"," to Avoid (Amazon only)"], editable:1},
skill_Penetrate:{index:["skill_Penetrate"], format:["+"," to Penetrate (Amazon only)"], editable:1},
skill_Evade:{index:["skill_Evade"], format:["+"," to Evade (Amazon only)"], editable:1},
skill_Decoy:{index:["skill_Decoy"], format:["+"," to Decoy (Amazon only)"], editable:1},
skill_Valkyrie:{index:["skill_Valkyrie"], format:["+"," to Valkyrie (Amazon only)"], editable:1},
skill_Pierce:{index:["skill_Pierce"], format:["+"," to Pierce (Amazon only)"], editable:1},
skill_Cold_Arrow:{index:["skill_Cold_Arrow"], format:["+"," to Cold Arrow (Amazon only)"], editable:1},
skill_Magic_Arrow:{index:["skill_Magic_Arrow"], format:["+"," to Magic Arrow (Amazon only)"], editable:1},
skill_Multiple_Shot:{index:["skill_Multiple_Shot"], format:["+"," to Multiple Shot (Amazon only)"], editable:1},
skill_Fire_Arrow:{index:["skill_Fire_Arrow"], format:["+"," to Fire Arrow (Amazon only)"], editable:1},
skill_Ice_Arrow:{index:["skill_Ice_Arrow"], format:["+"," to Ice Arrow (Amazon only)"], editable:1},
skill_Guided_Arrow:{index:["skill_Guided_Arrow"], format:["+"," to Guided Arrow (Amazon only)"], editable:1},
skill_Exploding_Arrow:{index:["skill_Exploding_Arrow"], format:["+"," to Exploding Arrow (Amazon only)"], editable:1},
skill_Strafe:{index:["skill_Strafe"], format:["+"," to Strafe (Amazon only)"], editable:1},
skill_Immolation_Arrow:{index:["skill_Immolation_Arrow"], format:["+"," to Immolation Arrow (Amazon only)"], editable:1},
skill_Freezing_Arrow:{index:["skill_Freezing_Arrow"], format:["+"," to Freezing Arrow (Amazon only)"], editable:1},

skill_Dual_Strike:{index:["skill_Dual_Strike"], format:["+"," to Dual Strike (Assassin only)"], editable:1},
skill_Fists_of_Ember:{index:["skill_Fists_of_Ember"], format:["+"," to Fists of Ember (Assassin only)"], editable:1},
skill_Fists_of_Fire:{index:["skill_Fists_of_Fire"], format:["+"," to Fists of Fire (Assassin only)"], editable:1},
skill_Fists_of_Thunder:{index:["skill_Fists_of_Thunder"], format:["+"," to Fists of Thunder (Assassin only)"], editable:1},
skill_Claws_of_Thunder:{index:["skill_Claws_of_Thunder"], format:["+"," to Claws of Thunder (Assassin only)"], editable:1},
skill_Fists_of_Ice:{index:["skill_Fists_of_Ice"], format:["+"," to Fists of Ice (Assassin only)"], editable:1},
skill_Static_Strike:{index:["skill_Static_Strike"], format:["+"," to Static Strike (Assassin only)"], editable:1},
skill_Dragon_Talon:{index:["skill_Dragon_Talon"], format:["+"," to Dragon Talon (Assassin only)"], editable:1},
skill_Emberstorm:{index:["skill_Emberstorm"], format:["+"," to Emberstorm (Assassin only)"], editable:1},
skill_Dragon_Flight:{index:["skill_Dragon_Flight"], format:["+"," to Dragon Flight (Assassin only)"], editable:1},
skill_Blades_of_Ice:{index:["skill_Blades_of_Ice"], format:["+"," to Blades of Ice (Assassin only)"], editable:1},
skill_Claw_Mastery:{index:["skill_Claw_Mastery"], format:["+"," to Claw Mastery (Assassin only)"], editable:1},
skill_Psychic_Hammer:{index:["skill_Psychic_Hammer"], format:["+"," to Psychic Hammer (Assassin only)"], editable:1},
skill_Burst_of_Speed:{index:["skill_Burst_of_Speed"], format:["+"," to Burst of Speed (Assassin only)"], editable:1},
skill_Mind_Barrier:{index:["skill_Mind_Barrier"], format:["+"," to Mind Barrier (Assassin only)"], editable:1},
skill_Weapon_Block:{index:["skill_Weapon_Block"], format:["+"," to Weapon Block (Assassin only)"], editable:1},
skill_Cloak_of_Shadows:{index:["skill_Cloak_of_Shadows"], format:["+"," to Cloak of Shadows (Assassin only)"], editable:1},
skill_Fade:{index:["skill_Fade"], format:["+"," to Fade (Assassin only)"], editable:1},
skill_Shadow_Warrior:{index:["skill_Shadow_Warrior"], format:["+"," to Shadow Warrior (Assassin only)"], editable:1},
skill_Mind_Blast:{index:["skill_Mind_Blast"], format:["+"," to Mind Blast (Assassin only)"], editable:1},
skill_Venom:{index:["skill_Venom"], format:["+"," to Venom (Assassin only)"], editable:1},
skill_Shadow_Master:{index:["skill_Shadow_Master"], format:["+"," to Shadow Master (Assassin only)"], editable:1},
skill_Fire_Blast:{index:["skill_Fire_Blast"], format:["+"," to Fire Blast (Assassin only)"], editable:1},
skill_Shock_Web:{index:["skill_Shock_Web"], format:["+"," to Shock Web (Assassin only)"], editable:1},
skill_Blade_Throw:{index:["skill_Blade_Throw"], format:["+"," to Blade Throw (Assassin only)"], editable:1},
skill_Charged_Bolt_Sentry:{index:["skill_Charged_Bolt_Sentry"], format:["+"," to Charged Bolt Sentry (Assassin only)"], editable:1},
skill_Wake_of_Fire:{index:["skill_Wake_of_Fire"], format:["+"," to Wake of Fire (Assassin only)"], editable:1},
skill_Blade_Fury:{index:["skill_Blade_Fury"], format:["+"," to Blade Fury (Assassin only)"], editable:1},
skill_Lightning_Sentry:{index:["skill_Lightning_Sentry"], format:["+"," to Lightning Sentry (Assassin only)"], editable:1},
skill_Wake_of_Inferno:{index:["skill_Wake_of_Inferno"], format:["+"," to Wake of Inferno (Assassin only)"], editable:1},
skill_Death_Sentry:{index:["skill_Death_Sentry"], format:["+"," to Death Sentry (Assassin only)"], editable:1},
skill_Blade_Shield:{index:["skill_Blade_Shield"], format:["+"," to Blade Shield (Assassin only)"], editable:1},
skill_Dragon_Tail:{index:["skill_Dragon_Tail"], format:["+"," to Dragon Tail (Assassin only)"], editable:1},

skill_Howl:{index:["skill_Howl"], format:["+"," to Howl (Barbarian only)"], editable:1},
skill_Find_Potion:{index:["skill_Find_Potion"], format:["+"," to Find Potion (Barbarian only)"], editable:1},
skill_Taunt:{index:["skill_Taunt"], format:["+"," to Taunt (Barbarian only)"], editable:1},
skill_Shout:{index:["skill_Shout"], format:["+"," to Shout (Barbarian only)"], editable:1},
skill_Find_Item:{index:["skill_Find_Item"], format:["+"," to Find Item (Barbarian only)"], editable:1},
skill_Battle_Cry:{index:["skill_Battle_Cry"], format:["+"," to Battle Cry (Barbarian only)"], editable:1},
skill_Battle_Orders:{index:["skill_Battle_Orders"], format:["+"," to Battle Orders (Barbarian only)"], editable:1},
skill_Grim_Ward:{index:["skill_Grim_Ward"], format:["+"," to Grim Ward (Barbarian only)"], editable:1},
skill_War_Cry:{index:["skill_War_Cry"], format:["+"," to War Cry (Barbarian only)"], editable:1},
skill_Battle_Command:{index:["skill_Battle_Command"], format:["+"," to Battle Command (Barbarian only)"], editable:1},
skill_Edged_Weapon_Mastery:{index:["skill_Edged_Weapon_Mastery"], format:["+"," to Edged Weapon Mastery (Barbarian only)"], editable:1},
skill_Pole_Weapon_Mastery:{index:["skill_Pole_Weapon_Mastery"], format:["+"," to Pole Weapon Mastery (Barbarian only)"], editable:1},
skill_Blunt_Weapon_Mastery:{index:["skill_Blunt_Weapon_Mastery"], format:["+"," to Blunt Weapon Mastery (Barbarian only)"], editable:1},
skill_Thrown_Weapon_Mastery:{index:["skill_Thrown_Weapon_Mastery"], format:["+"," to Thrown Weapon Mastery (Barbarian only)"], editable:1},
skill_Increased_Stamina:{index:["skill_Increased_Stamina"], format:["+"," to Increased Stamina (Barbarian only)"], editable:1},
skill_Iron_Skin:{index:["skill_Iron_Skin"], format:["+"," to Iron Skin (Barbarian only)"], editable:1},
skill_Increased_Speed:{index:["skill_Increased_Speed"], format:["+"," to Increased Speed (Barbarian only)"], editable:1},
skill_Natural_Resistance:{index:["skill_Natural_Resistance"], format:["+"," to Natural Resistance (Barbarian only)"], editable:1},
skill_Puncture:{index:["skill_Puncture"], format:["+"," to Puncture (Barbarian only)"], editable:1},
skill_Whirling_Axes:{index:["skill_Whirling_Axes"], format:["+"," to Whirling Axes (Barbarian only)"], editable:1},
skill_Double_Swing:{index:["skill_Double_Swing"], format:["+"," to Double Swing (Barbarian only)"], editable:1},
skill_Frenzy:{index:["skill_Frenzy"], format:["+"," to Frenzy (Barbarian only)"], editable:1},
skill_Concentrate:{index:["skill_Concentrate"], format:["+"," to Concentrate (Barbarian only)"], editable:1},
skill_Cleave:{index:["skill_Cleave"], format:["+"," to Cleave (Barbarian only)"], editable:1},
skill_Stun:{index:["skill_Stun"], format:["+"," to Stun (Barbarian only)"], editable:1},
skill_Leap:{index:["skill_Leap"], format:["+"," to Leap (Barbarian only)"], editable:1},
skill_Leap_Slam:{index:["skill_Leap_Slam"], format:["+"," to Leap Slam (Barbarian only)"], editable:1},
skill_Power_Throw:{index:["skill_Power_Throw"], format:["+"," to Power Throw (Barbarian only)"], editable:1},
skill_Bash:{index:["skill_Bash"], format:["+"," to Bash (Barbarian only)"], editable:1},
skill_Leap_Attack:{index:["skill_Leap_Attack"], format:["+"," to Leap Attack (Barbarian only)"], editable:1},
skill_Ethereal_Throw:{index:["skill_Ethereal_Throw"], format:["+"," to Ethereal Throw (Barbarian only)"], editable:1},
skill_Whirlwind:{index:["skill_Whirlwind"], format:["+"," to Whirlwind (Barbarian only)"], editable:1},
skill_One_Handed_Weapon_Mastery:{index:["skill_One_Handed_Weapon_Mastery"], format:["+"," to One Handed Weapon Mastery (Barbarian only)"], editable:1},
skill_Two_Handed_Weapon_Mastery:{index:["skill_Two_Handed_Weapon_Mastery"], format:["+"," to Two Handed Weapon Mastery (Barbarian only)"], editable:1},
skill_Deep_Wounds:{index:["skill_Deep_Wounds"], format:["+"," to Deep Wounds (Barbarian only)"], editable:1},
skill_Holy_Sword:{index:["skill_Holy_Sword"], format:["+"," to Holy Sword (Paladin only)"], editable:1},

skill_Firestorm:{index:["skill_Firestorm"], format:["+"," to Firestorm (Druid only)"], editable:1},
skill_Molten_Boulder:{index:["skill_Molten_Boulder"], format:["+"," to Molten Boulder (Druid only)"], editable:1},
skill_Flame_Dash:{index:["skill_Flame_Dash"], format:["+"," to Flame Dash (Druid only)"], editable:1},
skill_Arctic_Blast:{index:["skill_Arctic_Blast"], format:["+"," to Arctic Blast (Druid only)"], editable:1},
skill_Fissure:{index:["skill_Fissure"], format:["+"," to Fissure (Druid only)"], editable:1},
skill_Cyclone_Armor:{index:["skill_Cyclone_Armor"], format:["+"," to Cyclone Armor (Druid only)"], editable:1},
skill_Twister:{index:["skill_Twister"], format:["+"," to Twister (Druid only)"], editable:1},
skill_Volcano:{index:["skill_Volcano"], format:["+"," to Volcano (Druid only)"], editable:1},
skill_Tornado:{index:["skill_Tornado"], format:["+"," to Tornado (Druid only)"], editable:1},
skill_Armageddon:{index:["skill_Armageddon"], format:["+"," to Armageddon (Druid only)"], editable:1},
skill_Hurricane:{index:["skill_Hurricane"], format:["+"," to Hurricane (Druid only)"], editable:1},
skill_Werewolf:{index:["skill_Werewolf"], format:["+"," to Werewolf (Druid only)"], editable:1},
skill_Lycanthropy:{index:["skill_Lycanthropy"], format:["+"," to Lycanthropy (Druid only)"], editable:1},
skill_Werebear:{index:["skill_Werebear"], format:["+"," to Werebear (Druid only)"], editable:1},
skill_Feral_Rage:{index:["skill_Feral_Rage"], format:["+"," to Feral Rage (Druid only)"], editable:1},
skill_Maul:{index:["skill_Maul"], format:["+"," to Maul (Druid only)"], editable:1},
skill_Rabies:{index:["skill_Rabies"], format:["+"," to Rabies (Druid only)"], editable:1},
skill_Fire_Claws:{index:["skill_Fire_Claws"], format:["+"," to Fire Claws (Druid only)"], editable:1},
skill_Hunger:{index:["skill_Hunger"], format:["+"," to Hunger (Druid only)"], editable:1},
skill_Shock_Wave:{index:["skill_Shock_Wave"], format:["+"," to Shock Wave (Druid only)"], editable:1},
skill_Fury:{index:["skill_Fury"], format:["+"," to Fury (Druid only)"], editable:1},
skill_Raven:{index:["skill_Raven"], format:["+"," to Raven (Druid only)"], editable:1},
skill_Poison_Creeper:{index:["skill_Poison_Creeper"], format:["+"," to Poison Creeper (Druid only)"], editable:1},
skill_Heart_of_Wolverine:{index:["skill_Heart_of_Wolverine"], format:["+"," to Heart of Wolverine (Druid only)"], editable:1},
skill_Summon_Spirit_Wolf:{index:["skill_Summon_Spirit_Wolf"], format:["+"," to Summon Spirit Wolf (Druid only)"], editable:1},
skill_Carrion_Vine:{index:["skill_Carrion_Vine"], format:["+"," to Carrion Vine (Druid only)"], editable:1},
skill_Oak_Sage:{index:["skill_Oak_Sage"], format:["+"," to Oak Sage (Druid only)"], editable:1},
skill_Summon_Dire_Wolf:{index:["skill_Summon_Dire_Wolf"], format:["+"," to Summon Dire Wolf (Druid only)"], editable:1},
skill_Solar_Creeper:{index:["skill_Solar_Creeper"], format:["+"," to Solar Creeper (Druid only)"], editable:1},
skill_Spirit_of_Barbs:{index:["skill_Spirit_of_Barbs"], format:["+"," to Spirit of Barbs (Druid only)"], editable:1},
skill_Summon_Grizzly:{index:["skill_Summon_Grizzly"], format:["+"," to Summon Grizzly (Druid only)"], editable:1},

skill_Summon_Mastery:{index:["skill_Summon_Mastery"], format:["+"," to Summon Mastery (Necromancer only)"], editable:1},
skill_Raise_Skeleton_Warrior:{index:["skill_Raise_Skeleton_Warrior"], format:["+"," to Raise Skeleton Warrior (Necromancer only)"], editable:1},
skill_Bone_Offering:{index:["skill_Bone_Offering"], format:["+"," to Bone Offering (Necromancer only)"], editable:1},
skill_Clay_Golem:{index:["skill_Clay_Golem"], format:["+"," to Clay Golem (Necromancer only)"], editable:1},
skill_Flesh_Offering:{index:["skill_Flesh_Offering"], format:["+"," to Flesh Offering (Necromancer only)"], editable:1},
skill_Raise_Skeletal_Mage:{index:["skill_Raise_Skeletal_Mage"], format:["+"," to Raise Skeletal Mage (Necromancer only)"], editable:1},
skill_Blood_Golem:{index:["skill_Blood_Golem"], format:["+"," to Blood Golem (Necromancer only)"], editable:1},
skill_Convocation:{index:["skill_Convocation"], format:["+"," to Convocation (Necromancer only)"], editable:1},
skill_Iron_Golem:{index:["skill_Iron_Golem"], format:["+"," to Iron Golem (Necromancer only)"], editable:1},
skill_Fire_Golem:{index:["skill_Fire_Golem"], format:["+"," to Fire Golem (Necromancer only)"], editable:1},
skill_Revive:{index:["skill_Revive"], format:["+"," to Revive (Necromancer only)"], editable:1},
skill_Deadly_Poison:{index:["skill_Deadly_Poison"], format:["+"," to Deadly Poison (Necromancer only)"], editable:1},
skill_Teeth:{index:["skill_Teeth"], format:["+"," to Teeth (Necromancer only)"], editable:1},
skill_Bone_Armor:{index:["skill_Bone_Armor"], format:["+"," to Bone Armor (Necromancer only)"], editable:1},
skill_Corpse_Explosion:{index:["skill_Corpse_Explosion"], format:["+"," to Corpse Explosion (Necromancer only)"], editable:1},
skill_Desecrate:{index:["skill_Desecrate"], format:["+"," to Desecrate (Necromancer only)"], editable:1},
skill_Bone_Spear:{index:["skill_Bone_Spear"], format:["+"," to Bone Spear (Necromancer only)"], editable:1},
skill_Bone_Wall:{index:["skill_Bone_Wall"], format:["+"," to Bone Wall (Necromancer only)"], editable:1},
skill_Bone_Spirit:{index:["skill_Bone_Spirit"], format:["+"," to Bone Spirit (Necromancer only)"], editable:1},
skill_Poison_Nova:{index:["skill_Poison_Nova"], format:["+"," to Poison Nova (Necromancer only)"], editable:1},
skill_Amplify_Damage:{index:["skill_Amplify_Damage"], format:["+"," to Amplify Damage (Necromancer only)"], editable:1},
skill_Dim_Vision:{index:["skill_Dim_Vision"], format:["+"," to Dim Vision (Necromancer only)"], editable:1},
skill_Hemorrhage:{index:["skill_Hemorrhage"], format:["+"," to Hemorrhage (Necromancer only)"], editable:1},
skill_Weaken:{index:["skill_Weaken"], format:["+"," to Weaken (Necromancer only)"], editable:1},
skill_Iron_Maiden:{index:["skill_Iron_Maiden"], format:["+"," to Iron Maiden (Necromancer only)"], editable:1},
skill_Terror:{index:["skill_Terror"], format:["+"," to Terror (Necromancer only)"], editable:1},
skill_Confuse:{index:["skill_Confuse"], format:["+"," to Confuse (Necromancer only)"], editable:1},
skill_Life_Tap:{index:["skill_Life_Tap"], format:["+"," to Life Tap (Necromancer only)"], editable:1},
skill_Attract:{index:["skill_Attract"], format:["+"," to Attract (Necromancer only)"], editable:1},
skill_Decrepify:{index:["skill_Decrepify"], format:["+"," to Decrepify (Necromancer only)"], editable:1},
skill_Lower_Resist:{index:["skill_Lower_Resist"], format:["+"," to Lower Resist (Necromancer only)"], editable:1},

skill_Prayer:{index:["skill_Prayer"], format:["+"," to Prayer (Paladin only)"], editable:1},
skill_Resist_Fire:{index:["skill_Resist_Fire"], format:["+"," to Resist Fire (Paladin only)"], editable:1},
skill_Defiance:{index:["skill_Defiance"], format:["+"," to Defiance (Paladin only)"], editable:1},
skill_Resist_Cold:{index:["skill_Resist_Cold"], format:["+"," to Resist Cold (Paladin only)"], editable:1},
skill_Cleansing:{index:["skill_Cleansing"], format:["+"," to Cleansing (Paladin only)"], editable:1},
skill_Resist_Lightning:{index:["skill_Resist_Lightning"], format:["+"," to Resist Lightning (Paladin only)"], editable:1},
skill_Vigor:{index:["skill_Vigor"], format:["+"," to Vigor (Paladin only)"], editable:1},
skill_Meditation:{index:["skill_Meditation"], format:["+"," to Meditation (Paladin only)"], editable:1},
skill_Redemption:{index:["skill_Redemption"], format:["+"," to Redemption (Paladin only)"], editable:1},
skill_Salvation:{index:["skill_Salvation"], format:["+"," to Salvation (Paladin only)"], editable:1},
skill_Might:{index:["skill_Might"], format:["+"," to Might (Paladin only)"], editable:1},
skill_Holy_Fire:{index:["skill_Holy_Fire"], format:["+"," to Holy Fire (Paladin only)"], editable:1},
skill_Precision:{index:["skill_Precision"], format:["+"," to Precision (Paladin only)"], editable:1},
skill_Blessed_Aim:{index:["skill_Blessed_Aim"], format:["+"," to Blessed Aim (Paladin only)"], editable:1},
skill_Concentration:{index:["skill_Concentration"], format:["+"," to Concentration (Paladin only)"], editable:1},
skill_Holy_Freeze:{index:["skill_Holy_Freeze"], format:["+"," to Holy Freeze (Paladin only)"], editable:1},
skill_Holy_Shock:{index:["skill_Holy_Shock"], format:["+"," to Holy Shock (Paladin only)"], editable:1},
skill_Sanctuary:{index:["skill_Sanctuary"], format:["+"," to Sanctuary (Paladin only)"], editable:1},
skill_Fanaticism:{index:["skill_Fanaticism"], format:["+"," to Fanaticism (Paladin only)"], editable:1},
skill_Conviction:{index:["skill_Conviction"], format:["+"," to Conviction (Paladin only)"], editable:1},
skill_Sacrifice:{index:["skill_Sacrifice"], format:["+"," to Sacrifice (Paladin only)"], editable:1},
skill_Smite:{index:["skill_Smite"], format:["+"," to Smite (Paladin only)"], editable:1},
skill_Holy_Bolt:{index:["skill_Holy_Bolt"], format:["+"," to Holy Bolt (Paladin only)"], editable:1},
skill_Zeal:{index:["skill_Zeal"], format:["+"," to Zeal (Paladin only)"], editable:1},
skill_Charge:{index:["skill_Charge"], format:["+"," to Charge (Paladin only)"], editable:1},
skill_Vengeance:{index:["skill_Vengeance"], format:["+"," to Vengeance (Paladin only)"], editable:1},
skill_Blessed_Hammer:{index:["skill_Blessed_Hammer"], format:["+"," to Blessed Hammer (Paladin only)"], editable:1},
skill_Conversion:{index:["skill_Conversion"], format:["+"," to Conversion (Paladin only)"], editable:1},
skill_Holy_Shield:{index:["skill_Holy_Shield"], format:["+"," to Holy Shield (Paladin only)"], editable:1},
skill_Fist_of_the_Heavens:{index:["skill_Fist_of_the_Heavens"], format:["+"," to Fist of the Heavens (Paladin only)"], editable:1},
skill_Dashing_Strike:{index:["skill_Dashing_Strike"], format:["+"," to Dashing Strike (Paladin only)"], editable:1},

skill_Ice_Bolt:{index:["skill_Ice_Bolt"], format:["+"," to Ice Bolt (Sorceress only)"], editable:1},
skill_Frigerate:{index:["skill_Frigerate"], format:["+"," to Frigerate (Sorceress only)"], editable:1},
skill_Frost_Nova:{index:["skill_Frost_Nova"], format:["+"," to Frost Nova (Sorceress only)"], editable:1},
skill_Ice_Blast:{index:["skill_Ice_Blast"], format:["+"," to Ice Blast (Sorceress only)"], editable:1},
skill_Shiver_Armor:{index:["skill_Shiver_Armor"], format:["+"," to Shiver Armor (Sorceress only)"], editable:1},
skill_Glacial_Spike:{index:["skill_Glacial_Spike"], format:["+"," to Glacial Spike (Sorceress only)"], editable:1},
skill_Blizzard:{index:["skill_Blizzard"], format:["+"," to Blizzard (Sorceress only)"], editable:1},
skill_Freezing_Pulse:{index:["skill_Freezing_Pulse"], format:["+"," to Freezing Pulse (Sorceress only)"], editable:1},
skill_Chilling_Armor:{index:["skill_Chilling_Armor"], format:["+"," to Chilling Armor (Sorceress only)"], editable:1},
skill_Frozen_Orb:{index:["skill_Frozen_Orb"], format:["+"," to Frozen Orb (Sorceress only)"], editable:1},
skill_Cold_Mastery:{index:["skill_Cold_Mastery"], format:["+"," to Cold Mastery (Sorceress only)"], editable:1},
skill_Charged_Bolt:{index:["skill_Charged_Bolt"], format:["+"," to Charged Bolt (Sorceress only)"], editable:1},
skill_Static_Field:{index:["skill_Static_Field"], format:["+"," to Static Field (Sorceress only)"], editable:1},
skill_Telekinesis:{index:["skill_Telekinesis"], format:["+"," to Telekinesis (Sorceress only)"], editable:1},
skill_Nova:{index:["skill_Nova"], format:["+"," to Nova (Sorceress only)"], editable:1},
skill_Lightning_Surge:{index:["skill_Lightning_Surge"], format:["+"," to Lightning Surge (Sorceress only)"], editable:1},
skill_Chain_Lightning:{index:["skill_Chain_Lightning"], format:["+"," to Chain Lightning (Sorceress only)"], editable:1},
skill_Teleport:{index:["skill_Teleport"], format:["+"," to Teleport (Sorceress only)"], editable:1},
skill_Discharge:{index:["skill_Discharge"], format:["+"," to Discharge (Sorceress only)"], editable:1},
skill_Energy_Shield:{index:["skill_Energy_Shield"], format:["+"," to Energy Shield (Sorceress only)"], editable:1},
skill_Lightning_Mastery:{index:["skill_Lightning_Mastery"], format:["+"," to Lightning Mastery (Sorceress only)"], editable:1},
skill_Thunder_Storm:{index:["skill_Thunder_Storm"], format:["+"," to Thunder Storm (Sorceress only)"], editable:1},
skill_Fire_Bolt:{index:["skill_Fire_Bolt"], format:["+"," to Fire Bolt (Sorceress only)"], editable:1},
skill_Warmth:{index:["skill_Warmth"], format:["+"," to Warmth (Sorceress only)"], editable:1},
skill_Blaze:{index:["skill_Blaze"], format:["+"," to Blaze (Sorceress only)"], editable:1},
skill_Inferno:{index:["skill_Inferno"], format:["+"," to Inferno (Sorceress only)"], editable:1},
skill_Immolate:{index:["skill_Immolate"], format:["+"," to Immolate (Sorceress only)"], editable:1},
skill_Fire_Ball:{index:["skill_Fire_Ball"], format:["+"," to Fire Ball (Sorceress only)"], editable:1},
skill_Fire_Wall:{index:["skill_Fire_Wall"], format:["+"," to Fire Wall (Sorceress only)"], editable:1},
skill_Enflame:{index:["skill_Enflame"], format:["+"," to Enflame (Sorceress only)"], editable:1},
skill_Meteor:{index:["skill_Meteor"], format:["+"," to Meteor (Sorceress only)"], editable:1},
skill_Fire_Mastery:{index:["skill_Fire_Mastery"], format:["+"," to Fire Mastery (Sorceress only)"], editable:1},
skill_Hydra:{index:["skill_Hydra"], format:["+"," to Hydra (Sorceress only)"], editable:1},

oskill_Warp:{index:["oskill_Warp"], format:["+"," to Warp"], friendly:["Warp oskill"], editable:1},
oskill_Ball_Lightning:{index:["oskill_Ball_Lightning"], format:["+"," to Ball Lightning"], friendly:["Ball Lightning oskill"], editable:1},
//oskill_Dangoon_Discharge_Proc:{index:["oskill_Dangoon_Discharge_Proc"], format:["+"," Dangoon Discharge Proc"]},
//oskill_DangoonChain_Proc:{index:["oskill_DangoonChain_Proc"], format:["+"," Dangoon Chain Proc"]},
//oskill_DestructionVolcano_Proc:{index:["oskill_DestructionVolcano_Proc"], format:["+"," Destruction Volcano Proc"]},
//oskill_DestructionMBoulder_Proc:{index:["oskill_DestructionMBoulder_Proc"], format:["+"," Destruction MBoulder Proc"]},
//oskill_DestructionNova_Proc:{index:["oskill_DestructionNova_Proc"], format:["+"," Destruction Nova Proc"]},
oskill_CTC_Volcano_Proc:{index:["oskill_CTC_Volcano_Proc"], format:["CTC level "," Volcano Proc"]},
oskill_CTC_MBoulder_Proc:{index:["oskill_CTC_MBoulder_Proc"], format:["CTC level "," MBoulder Proc"]},
oskill_CTC_Nova_Proc:{index:["oskill_CTC_Nova_Proc"], format:["CTC level "," Nova Proc"]},
oskill_CTC_Discharge_Proc:{index:["oskill_CTC_Discharge_Proc"], format:["CTC level "," Discharge Proc"]},
oskill_CTC_Chain_Light_Proc:{index:["oskill_CTC_Chain_Light_Proc"], format:["CTC level "," Chain Light Proc"]},
oskill_CTC_Fissure_Proc:{index:["oskill_CTC_Fissure_Proc"], format:["CTC level "," Fissure Proc"]},
oskill_CTC_Bone_Spear_Proc:{index:["oskill_CTC_Bone_Spear_Proc"], format:["CTC level "," Bone Spear Proc"]},
oskill_CTC_Poison_Nova_Proc:{index:["oskill_CTC_Poison_Nova_Proc"], format:["CTC level "," Poison Nova Proc"]},
oskill_CTC_Ball_Lightning_Proc:{index:["oskill_CTC_Ball_Lightning_Proc"], format:["CTC level "," CTC Ball Lightning Proc"]},

oskill_Inner_Sight:{index:["oskill_Inner_Sight"], format:["+"," to Inner Sight"], friendly:["Inner Sight oskill"], editable:1},
oskill_Evade:{index:["oskill_Evade"], format:["+"," to Evade"], friendly:["Evade oskill"], editable:1},
oskill_Lethal_Strike:{index:["oskill_Lethal_Strike"], format:["+"," to Lethal Strike"], friendly:["Lethal Strike oskill"], editable:1},
oskill_Valkyrie:{index:["oskill_Valkyrie"], format:["+"," to Valkyrie"], friendly:["Valkyrie oskill"], editable:1},
oskill_Magic_Arrow:{index:["oskill_Magic_Arrow"], format:["+"," to Magic Arrow"], friendly:["Magic Arrow oskill"], editable:1},
oskill_Guided_Arrow:{index:["oskill_Guided_Arrow"], format:["+"," to Guided Arrow"], friendly:["Guided Arrow oskill"], editable:1},
oskill_Multiple_Shot:{index:["oskill_Multiple_Shot"], format:["+"," to Multiple Shot"], friendly:["Multiple Shot oskill"], editable:1},
oskill_Immolation_Arrow:{index:["oskill_Immolation_Arrow"], format:["+"," to Immolation Arrow"], friendly:["Immolation Arrow oskill"], editable:1},

oskill_Battle_Command:{index:["oskill_Battle_Command"], format:["+"," to Battle Command"], friendly:["Battle Command oskill"], editable:1},
oskill_Battle_Orders:{index:["oskill_Battle_Orders"], format:["+"," to Battle Orders"], friendly:["Battle Orders oskill"], editable:1},
oskill_Battle_Cry:{index:["oskill_Battle_Cry"], format:["+"," to Battle Cry"], friendly:["Battle Cry oskill"], editable:1},
oskill_Bash:{index:["oskill_Bash"], format:["+"," to Bash"], friendly:["Bash oskill"], editable:1},
oskill_Edged_Weapon_Mastery:{index:["oskill_Edged_Weapon_Mastery"], format:["+"," to Edged Weapon Mastery"], friendly:["Edged Weapon Mastery oskill"], editable:1},
oskill_Whirling_Axes:{index:["oskill_Whirling_Axes"], format:["+"," to Whirling Axes"], friendly:["Whirling Axes oskill"], editable:1},

oskill_Lycanthropy:{index:["oskill_Lycanthropy"], format:["+"," to Lycanthropy"], friendly:["Lycanthropy oskill"], editable:1},
oskill_Werebear:{index:["oskill_Werebear"], format:["+"," to Werebear"], friendly:["Werebear oskill"], editable:1},
oskill_Werewolf:{index:["oskill_Werewolf"], format:["+"," to Werewolf"], friendly:["Werewolf oskill"], editable:1},
oskill_Feral_Rage:{index:["oskill_Feral_Rage"], format:["+"," to Feral Rage"], friendly:["Feral Rage oskill"], editable:1},
oskill_Flame_Dash:{index:["oskill_Flame_Dash"], format:["+"," to Flame Dash"], friendly:["Flame Dash oskill"], editable:1},
oskill_Summon_Dire_Wolf:{index:["oskill_Summon_Dire_Wolf"], format:["+"," to Summon Dire Wolf"], friendly:["Summon Dire Wolf oskill"], editable:1},
oskill_Armageddon:{index:["oskill_Armageddon"], format:["+"," to Armageddon"], friendly:["Armageddon oskill"], editable:1},

oskill_Desecrate:{index:["oskill_Desecrate"], format:["+"," to Desecrate"], friendly:["Desecrate oskill"], editable:1},

oskill_Zeal:{index:["oskill_Zeal"], format:["+"," to Zeal"], friendly:["Zeal oskill"], editable:1},
oskill_Vengeance:{index:["oskill_Vengeance"], format:["+"," to Vengeance"], friendly:["Vengeance oskill"], editable:1},
oskill_Dashing_Strike:{index:["oskill_Dashing_Strike"], format:["+"," to Dashing Strike"], friendly:["Dashing Strike oskill"], editable:1},
oskill_Concentration:{index:["oskill_Concentration"], format:["+"," to Concentration"], friendly:["Concentration oskill"], editable:1},


oskill_Frigerate:{index:["oskill_Frigerate"], format:["+"," to Frigerate"], friendly:["Frigerate oskill"], editable:1},
oskill_Shiver_Armor:{index:["oskill_Shiver_Armor"], format:["+"," to Shiver Armor"], friendly:["Shiver Armor oskill"], editable:1},
oskill_Cold_Mastery:{index:["oskill_Cold_Mastery"], format:["+"," to Cold Mastery"], friendly:["Cold Mastery oskill"], editable:1},
oskill_Hydra:{index:["oskill_Hydra"], format:["+"," to Hydra"], friendly:["Hydra oskill"], editable:1},
oskill_Fire_Ball:{index:["oskill_Fire_Ball"], format:["+"," to Fire Ball"], friendly:["Fire Ball oskill"], editable:1},
oskill_Fire_Wall:{index:["oskill_Fire_Wall"], format:["+"," to Fire Wall"], friendly:["Fire Wall oskill"], editable:1},
oskill_Meteor:{index:["oskill_Meteor"], format:["+"," to Meteor"], friendly:["Meteor oskill"], editable:1},
oskill_Fire_Mastery:{index:["oskill_Fire_Mastery"], format:["+"," to Fire Mastery"], friendly:["Fire Mastery oskill"], editable:1},
oskill_Blizzard:{index:["oskill_Blizzard"], format:["+"," to Blizzard"], friendly:["Blizzard oskill"], editable:1},

skills_class:{index:["skills_class"], format:["+"," to Class Skills"]},		// unneeded once item customization gets implemented
skills_tree1:{index:["skills_tree1"], format:["+"," to Tree #1 Skills"]},	// unused
skills_tree2:{index:["skills_tree2"], format:["+"," to Tree #2 Skills"]},	// unused
skills_tree3:{index:["skills_tree3"], format:["+"," to Tree #3 Skills"]},	// unused

//proc_Dangoon_Discharge:{index:["proc_Dangoon_Discharge"], format:["Discharge proc is +",21]},

stamina_skillup:{index:["stamina_skillup"], format:["+","% Stamina"]},
frw_skillup:{index:["frw_skillup"], format:["+","% Faster Run/Walk"], editable:1},
defense_skillup:{index:["defense_skillup"], format:["+","% Defense"], editable:1},
resistance_skillup:{index:["resistance_skillup"], format:["+","% Resistances"], editable:1},
cstrike_skillup:{index:["cstrike_skillup"], format:["+","% Critical Strike"], editable:1},
ar_skillup:{index:["ar_skillup"], format:["+","% Attack Rating"], editable:1},
pierce_skillup:{index:["pierce_skillup"], format:["+","% Pierce"]},
fRes_skillup:{index:["fRes_skillup"], format:["+","% Fire Resist"]},
cRes_skillup:{index:["cRes_skillup"], format:["+","% Cold Resist"]},
lRes_skillup:{index:["lRes_skillup"], format:["+","% Lightning Resist"]},
pRes_skillup:{index:["pRes_skillup"], format:["+","% Poison Resist"]},
block_skillup:{index:["block_skillup"], format:["Block Chance: ","%"]},
velocity_skillup:{index:["velocity_skillup"], format:["+","% Velocity"]},
dodge:{index:["dodge"], format:["+","% Dodge (against Melee Attacks when attacking or standing still)"]},
avoid:{index:["avoid"], format:["+","% Dodge (against Missile Attacks when attacking or standing still)"]},
evade:{index:["evade"], format:["+","% Dodge (when walking or running)"]},
edged_damage:{index:["edged_damage"], format:["+","% Damage"]},
edged_ar:{index:["edged_ar"], format:["+","% Attack Rating"]},
edged_cstrike:{index:["edged_cstrike"], format:["+","% Critical Strike"]},
pole_damage:{index:["pole_damage"], format:["+","% Damage"]},
pole_ar:{index:["pole_ar"], format:["+","% Attack Rating"]},
pole_cstrike:{index:["pole_cstrike"], format:["+","% Critical Strike"]},
blunt_damage:{index:["blunt_damage"], format:["+","% Damage"]},
blunt_ar:{index:["blunt_ar"], format:["+","% Attack Rating"]},
blunt_cstrike:{index:["blunt_cstrike"], format:["+","% Critical Strike"]},
thrown_damage:{index:["thrown_damage"], format:["+","% Damage"]},
thrown_ar:{index:["thrown_ar"], format:["+","% Attack Rating"]},
thrown_pierce:{index:["thrown_pierce"], format:["+","% Pierce"]},
claw_damage:{index:["claw_damage"], format:["+","% Damage"]},
claw_ar:{index:["claw_ar"], format:["+","% Attack Rating"]},
claw_cstrike:{index:["claw_cstrike"], format:["+","% Critical Strike"]},

summon_damage:{index:["summon_damage"], format:["Summons deal +","% Increased Damage"]},
summon_defense:{index:["summon_defense"], format:["Summons have +","% Enhanced Defense"]},
all_skills_per_level:{index:["all_skills_per_level"], format:["+"," to All Skills (based on character level)"], mult:["level"]},
reset_on_kill:{index:["reset_on_kill"], format:["Chance to Reset Duration on Kill: ","%"]},
explosive_attack:{index:[], format:["Fires Explosive Arrows or Bolts"]},
magic_attack:{index:[], format:["Fires Magic Arrows"]},

ctc_temp1:{index:[], format:["10% chance to cast level 15 Nova on striking"]},			// TODO: refine equip() & related functions to allow ctc affixes to function as item set bonuses  (M'avina's Caster)
ctc_temp2:{index:[], format:["25% chance to cast level 5 Static Field when struck"]},	// TODO: refine equip() & related functions to allow ctc affixes to function as shared set bonuses  (Cow King's Leathers)

ar_vs_demons_per_level:1,	// TODO: implement (vanilla affix found on Grief that was removed in PoD)
oskill_Whirlwind:{index:["oskill_Whirlwind"], format:["+"," to Whirlwind"], friendly:["Whirlwind oskill"], },
lDamage_max_per_level:{index:["lDamage_max_per_level","lDamage_max_per_level"], format:["+"," to Maximum Lightning Damage ("," per level)"], mult:["level",1]},

oskill_Heart_of_Wolverine:{index:["oskill_Heart_of_Wolverine"], format:["+"," to Heart of Wolverine"], friendly:["Heart of Wolverine oskill"], },

slow_ranged_attacks:{index:["slow_ranged_attacks"], format:["Ranged Attacks slowed to "," percent"]},

// TODO: implement these
skills_lightning_all:{index:["skills_lightning_all"], format:["+"," to Lightning Skills"]},
skills_magic_all:{index:["skills_magic_all"], format:["+"," to Magic Skills"]},
owounds_dps:{index:["owounds_dps"], format:["+"," Wounds Bleed Damage per second"]},
owounds_dps_per_level:{index:["owounds_dps_per_level","owounds_dps_per_level"], format:["+"," Wounds Bleed Damage per second ("," per level)"], mult:["level",1]},
extra_mainhand_attack:{index:["extra_mainhand_attack"], format:["","% Chance for additional mainhand attack"]},
mDamage_per_frenzy_charge:{index:["mDamage_per_frenzy_charge"], format:["+"," Magic Damage per Frenzy Charge"]},
frenzy_duration:{index:["frenzy_duration"], format:["+"," Seconds to Frenzy Duration"]},
thrown_cstrike:{index:["thrown_cstrike"], format:["+","% Critical Strike"]},
owounds_duration:{index:["owounds_duration"], format:["Wound Bleed Duration +"," seconds"]},
counterattack:{index:["counterattack"], format:["","% chance to counterattack"]},
added_whirlychance:{index:["added_whirlychance"], format:["","% added chance to release Whirling Axes"]},
whirlychance:{index:["whirlychance"], format:["","% chance to release Whirling Axes"]},
totalwhirly:{index:["totalwhirly"], format:["","% chance to release Whirling Axes"]},
synthfrom1:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Mang Song <br>Ondal's Wisdom <br>Arioc's Needle"+'</span>']},
synthfrom2:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Grandfather <br>Doombringer <br>Suicide Branch <br>Blackhand Key"+'</span>']},
synthfrom3:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Doomslinger <br>Death's Web <br>Arioc's Needle <br>Blackbog's Sharp"+'</span>']},
synthfrom4:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Thereal Edge <br>Tomb Reaver"+'</span>']},
synthfrom5:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Schaeffer's Hammer <br>Stormspire <br>Thunderstroke"+'</span>']},
synthfrom6:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Wizendraw <br>Hellrack <br>Mang Song"+'</span>']},
synthfrom7:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Gull <br>Tomb Reaver <br>Blade of Ali Baba"+'</span>']},
synthfrom8:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Tomb Reaver <br>Demon Limb <br>Skystrike"+'</span>']},
synthfrom9:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Mang Song <br>Ondal's Wisdom <br>Arioc's Needle"+'</span>']},
synthfrom10:{index:[], format:['<span style="color:#928068; font-size:12px">'+"Synthesized from: <br>Mang Song <br>Ondal's Wisdom <br>Arioc's Needle"+'</span>']},
multPierce:{index:["multPierce"], format:["Poison and Elemental Pierce multiplied by",""]},

// debug:{index:[],format:['<span style="color:red; font-size:12px">'+"Item does not exist in game,<br>only exists here for ease of testing"+'</span>']},


pulverize:{index:["pulverize"], format:["","% chance to pulverize"]},
charge_tiger:{index:["charge_tiger"], format:[""," Tiger Charges"]},
charge_cobra:{index:["charge_cobra"], format:[""," Cobra Charges"]},
charge_bonus_explosion:{index:[], format:["Attacks cause explosions"]},
charge_bonus_meteor:{index:[], format:["Attacks summon meteors"]},
charge_bonus_fork:{index:[], format:["Attacks release forked lightning"]},
charge_bonus_static:{index:[], format:["Attacks cast static field"]},
charge_bonus_icicles:{index:[], format:["Attacks release enemy-seeking icicles"]},
charge_bonus_accuracy:{index:[], format:["Attacks have increased accuracy"]},
charge_bonus_reduce:{index:[], format:["Attacks reduce enemy defenses"]},
charge_bonus_leech:{index:[], format:["Attacks regenerate life and mana"]},

// Start adding Patch 22 content below
plus_arrow_radius:{index:["plus_arrow_radius"], format:["+","% to "," Arrow Radius"]},
oskill_Warmth:{index:["oskill_Warmth"], format:["+"," to Warmth"], friendly:["Warmth oskill"], editable:1},
plus_exploding_arrow_radius:{index:["plus_exploding_arrow_radius"], format:["+","% to Exploding Arrow Radius"], editable:1},
plus_freezing_arrow_radius:{index:["plus_freezing_arrow_radius"], format:["+","% to Freezing Arrow Radius"], editable:1},
oskill_Deadly_Poison:{index:["oskill_Deadly_Poison"], format:["+"," to Deadly Poison"], friendly:["Deadly Poison oskill"], editable:1},
oskill_Charge:{index:["oskill_Charge"], format:["+"," to Charge"], friendly:["Charge oskill"], editable:1},
tigerstrike_boi:{index:[], format:["Tiger Strike also generates a Blades of Ice charge"]},
extra_tk:{index:[], format:["Releases one additional Telekinesis burst"]},
oskill_Telekinesis:{index:["oskill_Telekinesis"], format:["+"," to Telekinesis"], friendly:["Telekinesis oskill"], editable:1},
oskill_Strafe:{index:["oskill_Strafe"], format:["+"," to Strafe"], friendly:["Strafe oskill"], editable:1},
nova_bong:{index:[], format:["Casting Frost Nova also casts Nova"]},
all_sorb:{index:["all_sorb"], format:["Damage Absorb: ","%"], editable:1},
thunder_warp:{index:[], format:["Thunder storm strikes two additional enemies"]},
jf_molten:{index:[], format:["Jab & Fend attacks cast molten strike"]},
hf_incrased_rate:{index:[], format:["+50% increased Holy Fire Area Damage rate"]},
oskill_Revive:{index:["oskill_Revive"], format:["+"," to Revive"], friendly:["Revive oskill"], editable:1},
tigerstrike_fof:{index:[], format:["Tiger Strike also generates a Fists of Fire Charge"]},
skill_Double_Throw:{index:["skill_Double_Throw"], format:["+"," to Double Throw (Barbarian only)"], editable:1},
summon_more_shadow:{index:[], format:["Can Summon an Additional Shadow Warrior/Master"], editable:1},
lDamage_max_per_2_dex:{index:["lDamage_max_per_2_dex"], format:["+"," Lightning Damage per 2 Dexterity"], editable:1},
skills_summon_all:{index:["skills_summon_all"], format:["+"," to Summon Skills"], editable:1},
mosaic_charge_dur:{index:["mosaic_charge_dur"], format:["+"," Seconds to All Martial Arts Charges Duration"], editable:1},
oskill_Taunt:{index:["oskill_Taunt"], format:["+"," to Taunt"], friendly:["Taunt oskill"], editable:1},
oskill_Blood_Golem:{index:["oskill_Blood_Golem"], format:["+"," to Blood Golem"], friendly:["Blood Golem oskill"], editable:1},
placeholder:{index:[], format:["<font color='red'>Not all stats supported for import yet<br>You can add missing stats on right</font>"]},
rplaceholder:{index:[], format:["<font color='red'>Not all stats supported for import yet<br>You can add missing stats on right</font>"]},
cplaceholder:{index:[], format:["<font color='red'>Not all stats supported for import yet<br>You can add missing stats on right</font>"]},
invisphys:{index:[], format:[""]},
pAbsorb:{index:["pAbsorb"], format:["Physical Absorb ","%"], editable:1},
easymathdmg:{index:[], format:["<font color='red'>100 Base Damage for easy math</font>"]},
obsessiontheory:{index:[], format:["<font color='red'>Theorycrafting Obsession ideas<br>Check the discord channel for more info</font>"]},
maul_charges:{index:["maul_charges"], format:[""," Max Maul charges"]},
oskill_Cleave:{index:["oskill_Cleave"], format:["+"," to Cleave"]},
addeddmgdisplaywrong:{index:[], format:["<font color='red'><br>Display of aura damage added to attack display <b>in this pop up</b> is not<br>properly reflecting % elemental modifiers<br>Aura tick display is correct, overall added damage is correct</font>"]},

addcraft:{index:[], format:[]},
customStats:"",
emptysynth:{index:[], format:["<font color='red'>Synth items might be imported missing stats<br>Add missing stats on right</font>"]},

};